/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/student/route'
import { Route as AuthenticatedTeachRouteRouteImport } from './routes/_authenticated/teach/route'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedStudentBrowseRouteImport } from './routes/_authenticated/student/browse'
import { Route as AuthenticatedStudentLearningRouteImport } from './routes/_authenticated/student/learning'
import { Route as AuthenticatedTeachIndexRouteImport } from './routes/_authenticated/teach/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachRouteRoute = AuthenticatedTeachRouteRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentBrowseRoute =
  AuthenticatedStudentBrowseRouteImport.update({
    id: '/browse',
    path: '/browse',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentLearningRoute =
  AuthenticatedStudentLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedTeachIndexRoute = AuthenticatedTeachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTeachRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/teach': typeof AuthenticatedTeachRouteRouteWithChildren
  '/student/browse': typeof AuthenticatedStudentBrowseRoute
  '/student/learning': typeof AuthenticatedStudentLearningRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/teach/': typeof AuthenticatedTeachIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student/browse': typeof AuthenticatedStudentBrowseRoute
  '/student/learning': typeof AuthenticatedStudentLearningRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/teach': typeof AuthenticatedTeachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/teach': typeof AuthenticatedTeachRouteRouteWithChildren
  '/_authenticated/student/browse': typeof AuthenticatedStudentBrowseRoute
  '/_authenticated/student/learning': typeof AuthenticatedStudentLearningRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/teach/': typeof AuthenticatedTeachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/student'
    | '/teach'
    | '/student/browse'
    | '/student/learning'
    | '/student/'
    | '/teach/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/student/browse'
    | '/student/learning'
    | '/student'
    | '/teach'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/student'
    | '/_authenticated/teach'
    | '/_authenticated/student/browse'
    | '/_authenticated/student/learning'
    | '/_authenticated/student/'
    | '/_authenticated/teach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teach': {
      id: '/_authenticated/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof AuthenticatedTeachRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/browse': {
      id: '/_authenticated/student/browse'
      path: '/browse'
      fullPath: '/student/browse'
      preLoaderRoute: typeof AuthenticatedStudentBrowseRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/learning': {
      id: '/_authenticated/student/learning'
      path: '/learning'
      fullPath: '/student/learning'
      preLoaderRoute: typeof AuthenticatedStudentLearningRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/teach/': {
      id: '/_authenticated/teach/'
      path: '/'
      fullPath: '/teach/'
      preLoaderRoute: typeof AuthenticatedTeachIndexRouteImport
      parentRoute: typeof AuthenticatedTeachRouteRoute
    }
  }
}

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentBrowseRoute: typeof AuthenticatedStudentBrowseRoute
  AuthenticatedStudentLearningRoute: typeof AuthenticatedStudentLearningRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentBrowseRoute: AuthenticatedStudentBrowseRoute,
    AuthenticatedStudentLearningRoute: AuthenticatedStudentLearningRoute,
    AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedTeachRouteRouteChildren {
  AuthenticatedTeachIndexRoute: typeof AuthenticatedTeachIndexRoute
}

const AuthenticatedTeachRouteRouteChildren: AuthenticatedTeachRouteRouteChildren =
  {
    AuthenticatedTeachIndexRoute: AuthenticatedTeachIndexRoute,
  }

const AuthenticatedTeachRouteRouteWithChildren =
  AuthenticatedTeachRouteRoute._addFileChildren(
    AuthenticatedTeachRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedTeachRouteRoute: typeof AuthenticatedTeachRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedTeachRouteRoute: AuthenticatedTeachRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
